//frontend/src/redux/constants/mailConstants
export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAILURE = 'SEND_EMAIL_FAILURE';

export const RECEIVE_EMAILS_REQUEST = "RECEIVE_EMAILS_REQUEST";
export const RECEIVE_EMAILS_SUCCESS = "RECEIVE_EMAILS_SUCCESS";
export const RECEIVE_EMAILS_FAILURE  = "RECEIVE_EMAILS_FAILURE";

export const STAR_EMAIL_SUCCESS = 'STAR_EMAIL_SUCCESS';

export const FETCH_STARRED_EMAILS_REQUEST = 'FETCH_STARRED_EMAILS_REQUEST';
export const FETCH_STARRED_EMAILS_SUCCESS = 'FETCH_STARRED_EMAILS_SUCCESS';
export const FETCH_STARRED_EMAILS_FAILURE = 'FETCH_STARRED_EMAILS_FAILURE';

export const UNSTAR_EMAIL_SUCCESS = 'UNSTAR_EMAIL_SUCCESS'

export const FETCH_SENT_EMAILS_REQUEST = 'FETCH_SENT_EMAILS_REQUEST';
export const FETCH_SENT_EMAILS_SUCCESS = 'FETCH_SENT_EMAILS_SUCCESS'; 
export const FETCH_SENT_EMAILS_FAILURE = 'FETCH_SENT_EMAILS_FAILURE'; 

export const MOVE_TO_TRASH_SUCCESS = 'MOVE_TO_TRASH_SUCCESS';

export const FETCH_TRASH_EMAILS_REQUEST = 'FETCH_TRASH_EMAILS_REQUEST';
export const FETCH_TRASH_EMAILS_SUCCESS = 'FETCH_TRASH_EMAILS_SUCCESS';
export const FETCH_TRASH_EMAILS_FAILURE = 'FETCH_TRASH_EMAILS_FAILURE';

export const UNTRASH_EMAIL_SUCCESS = 'UNTRASH_EMAIL_SUCCESS';

export const DELETE_EMAIL_REQUEST = 'DELETE_EMAIL_REQUEST';
export const DELETE_EMAIL_SUCCESS = 'DELETE_EMAIL_SUCCESS';
export const DELETE_EMAIL_FAILURE = 'DELETE_EMAIL_FAILURE';